/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from "./routes/__root";
import { Route as VentesRouteImport } from "./routes/ventes";
import { Route as RegionsRouteImport } from "./routes/regions";
import { Route as RecouvrementRouteImport } from "./routes/recouvrement";
import { Route as ProduitsRouteImport } from "./routes/produits";
import { Route as ImpayesRouteImport } from "./routes/impayes";
import { Route as EcrituresRouteImport } from "./routes/ecritures";
import { Route as CommerciauxRouteImport } from "./routes/commerciaux";
import { Route as ClientsRouteImport } from "./routes/clients";
import { Route as AchatsRouteImport } from "./routes/achats";
import { Route as IndexRouteImport } from "./routes/index";
const VentesRoute = VentesRouteImport.update({
  id: "/ventes",
  path: "/ventes",
  getParentRoute: () => rootRouteImport,
});
const RegionsRoute = RegionsRouteImport.update({
  id: "/regions",
  path: "/regions",
  getParentRoute: () => rootRouteImport,
});
const RecouvrementRoute = RecouvrementRouteImport.update({
  id: "/recouvrement",
  path: "/recouvrement",
  getParentRoute: () => rootRouteImport,
});
const ProduitsRoute = ProduitsRouteImport.update({
  id: "/produits",
  path: "/produits",
  getParentRoute: () => rootRouteImport,
});
const ImpayesRoute = ImpayesRouteImport.update({
  id: "/impayes",
  path: "/impayes",
  getParentRoute: () => rootRouteImport,
});
const EcrituresRoute = EcrituresRouteImport.update({
  id: "/ecritures",
  path: "/ecritures",
  getParentRoute: () => rootRouteImport,
});
const CommerciauxRoute = CommerciauxRouteImport.update({
  id: "/commerciaux",
  path: "/commerciaux",
  getParentRoute: () => rootRouteImport,
});
const ClientsRoute = ClientsRouteImport.update({
  id: "/clients",
  path: "/clients",
  getParentRoute: () => rootRouteImport,
});
const AchatsRoute = AchatsRouteImport.update({
  id: "/achats",
  path: "/achats",
  getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AchatsRoute: AchatsRoute,
  ClientsRoute: ClientsRoute,
  CommerciauxRoute: CommerciauxRoute,
  EcrituresRoute: EcrituresRoute,
  ImpayesRoute: ImpayesRoute,
  ProduitsRoute: ProduitsRoute,
  RecouvrementRoute: RecouvrementRoute,
  RegionsRoute: RegionsRoute,
  VentesRoute: VentesRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
